'use client';
import React from 'react';
import { Inter } from 'next/font/google';
import StyledComponentsRegistry from '../lib/AntdRegistry';
// import '@/globals.css';
import { Layout, Menu } from 'antd';
import { Content, Footer, Header } from 'antd/es/layout/layout';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="en">
    <body className={inter.className}>
      <StyledComponentsRegistry>
        <Layout>
          <Header>
            <Menu>
              <Menu.Item key="1">
                <Link href="/">Home</Link>
              </Menu.Item>
              <Menu.Item key="2">
                <Link href="/about">About</Link>
              </Menu.Item>
              <Menu.Item key="3">
                <Link href="/">Home</Link>
              </Menu.Item>
            </Menu>
          </Header>
          <Content>

            {children}
          </Content>
          <Footer></Footer>
        </Layout>
      </StyledComponentsRegistry>
    </body>
  </html>
);

export default RootLayout;